export const USER_DETAILS = "USER_DETAILS";
export const USER_REGISTRATION = "USER_REGISTRATION";
export const USERS_INFO_SUCCESS = "USERS_INFO_SUCCESS";
export const USERS_INFO_FAILURE = "USERS_INFO_FAILURE";
export const USERS_INFO_PENDING = "USERS_INFO_PENDING";